language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "Epe3K9J8/TtrR/RnfLc4kTI8W9jHbW39riiaSqUTngnUL/NNNhIIMS1BEtqD6ALKM0cCMpWcFg/VAkbaLY75ExkBaE8T3tltjh/zPv3hv5Z4u6UfP7bIKHP55aplbph9YCl2ROQOWVvpHNauPR4OlQcEFymDeL3cl9dM4HvV6MeXERJwj8AzLzEmp41HHQgfVOFhomOHDIVMM9m10qA8LIVtb3F59SxcwvBJ143kV7D3oI1Xy4ChWRXHxkDOzVEVx6ADNnygT5yRKUwWb7IgvuozqvoKtddUV+89cYFt6yUt5b2mF6vcbwTyN3g7CwNDMn9uv3DyNmmItUAKEjtZ21bTVRdF0lhhNxIBPgcW9VYcmIo0oBG4tW+O0YDbVX9AfUego0zHAYUa9RFXUiwg/WetkPxs+urRpkck34ecXVIdCUf7/T12NuP/EhRdHX+9v5BitJZhxG2UoABw6uwnq8DKHQzJsP61IwaJOLa+JLSz2v9vcShTw9CjI/eZkR9x8qd9ZsShKh5eoW9COOjKFXn/HYMTKy+Ipz0MCFwyHViDrqQfLq5iCEgVHHHh/WEs6R3/oJvZLywyVR+EZ4+ObSOzCuES34XXZ+zEFj3wNCSvSjqAtqrl3TbnU/yCOXSvSu7REebj2Zs37Q+jVLXRcnlVXAcvFiFLDH3u2uyjv+U="
    # OSSRH_JIRA_PASSWORD
    - secure: "wGRSWxIeehKG2XjuwNs2ijutdJn6L8thHaOC9w1PDg5p4LwcWER+6g7qVVPvBBY0nZFP3GwIylcMmuV3DoYh4qIOeUPpyXL84Q5TDBP0WBQZ8o8mSx7b1MPxc6ztd6cvtWT9wNiTeaCkZfn2wm1CShkjFvE4EIgchgG+e9t8g05zJEjsvTAVN411cRnHNiN66yXY4WkMoPgoLWb59Zyo1AneYJpu9ZZtj74TrIrug2ff6vfFerxjh2q2D6ywcVJ2GUb0qAqGYtES3Oab3fct4WFQ4QpTpA7Z75vwFoDQlPBV6g+x9ubIg9A5TpPTUar2oRt6+0e6XkEdvU4YeaL1qKXpH39CCROwM0kPBBk1v2lEuKcZMyIne2BC8w2oAkWR0newRC7y+2DIyzS0JSBDZ6ueSYF2tMvTDUai5e+jK4y1caEJPeZ/D81KZ8wApyLK/FZcagM4iDO05RR3nvPzYewl6tBO1+sUwi9lNx62wpdDMoaUBIoqTTw4LXAkLw7M6QUKwy7R//02/ipY91Fx+3c+zY6kKZ/KYEl+alxSrVANwDfWL6cOTucStb7CZMdOlTC6IdpEfeco80GD3MQwC8c4aY+GMH415UaW2WKohW98ySUw2de655LGMjNK97bI2MBIww00KrInkGfc293Ohq1g1oA3Z7vnvrbk9bSxoWA="
      # GPG_KEY_NAME
    - secure: "Rj0tlObcIODyr8kuvwbqNMGWdxU4MXAR6oEsW2/jUmPaxJx5QZsC+3gYFtKD0oCYeHlayc0HOPGjjR7hThAQWRNN3n/ZIht+4BbBRBv9f3LEHp3jiA5CbiY8GyjT45Gr/Z4+S0D1wQE4rkqZtIuNC86NKKfFbRDC5DS4jwh89sbD9dabg/gejCu33ShByhIq8DgVP56SQzkILmojNNUT+csxao4GyPx9XdDKOzNMhB/OlLuiQ/37H5IK/kPlBtcwDd76vVVuYUYzc1VYB2HaOes3UDHCAoHFKZAJ9TZdpEn+HULjbLQtn+d81seKAEaIvSdBiXZ1Ri1ufRc33KZVyFrDDW8wtbtxiZZeLuvmDMmS0NiD4SvtD8rknjFL2nU9dTqXbDDYKr1esDTs0vOClMgAx03ppMnG5qBH2dKnx6jhGpEfPyLGB6h4fxK+S7CP8XVze/So81CcbppWmasEke8Fiv1sTQxRN18EAIXYq6jo4Kky+wBpIzFihdu67iP8xkL3gC8MiwwlPTE6s3wWg27m8lhXTo8RQjxwso1smbLo/h8KHYLRePT3cLZLnQHW/ebgplYoO3so1w1rUw0IwF4rGnsdT06ObMdFOYHPYyO8Qmzc+kO3Ak4enB2x9LsFJnfZhjlhTupmqje0yqkGlJv7lL8cv0cbU/7C+6AS3AY="
    # GPG_PASSPHRASE
    - secure: "aGysx9gKaM3eRct10xhFsNluwM2gD3rq/LHJw873p3dVSh8agxoCWDhfLNtup2dwJZnQF7Qao6d6NrCZQq0wICW+BEq3RSmhaWylu4ImBwILz8684LJI5U11Am5jroaWf0U8WcnL0y727D+gAXMqGJUL3LqKkoE+RiZgSPzC/3xWkkkKrXI9+FqeVu4KOGXQAOJUz3p/rywheXPjb1+cJIx3nSCyIfiXVP0PCIjB8638Fmx7Hob5zmLvKtIEB8DpxHlU1bTrnYsrPa/1VPNf8MZ+sFxeOZ3sO0ltrOIJpMP27RXmYMrpmFmQQZWvNOlk3aJ0JdzZp7BTHmOxBBDo5GdDrzIYl93FpnyME7hNntjfvLhag/q9/pVhFOTRwHxSKoJcR+0MiezA0qz/E3zNawhrY7ueNY8zvyyCfR9edA33aeECdqPgk87c+am52UQxRFGLTXJf7Efq991qmKjJC6RuCXRyms5OPN8VmS4AbUcXg4UNnW1c2hlcskdZj/jCCYB8NhVm9JKXkXSsIJ7PYkNNpj3jCgD55SPzrz20BWFczx+Fa1kllTUl2wy7LwqGW1U+5r8970EFEKbMYXAFd9dWh6VdUBFr7MHaNr49TIPg8jsSlpYhG2jtxvxRPc/pH+xXilJ+jQTxGoUMBoeOw4mqaQAYxEXavoq9WVW57/0="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
