language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "UZHvFtGtCiz72cq8R+igvvKWtHxV+UthL4QQFH1vuj2l1phSOCSVZAw973xW9MSEYE+ur6Tr+TSQ0er41uApdmq2gwcojH0xi6N4zfDKVC1q25p3v3p7PGsUPpIZeF9u5vbGIZGghfA/KJ4/Pb1aik9UIYO4kyL3GQPGaNw4ZrivEdvmzzWVSXUn25seZ5+XBNoLmi/mzWFJ7iy+cNTQCvc2ljMotpY6P9Fz4ZpFfDqUe35nVcXu6SmtjpxBIcATYlNrDOjCjIhRF0xtXxdik/RTFnod1REv6QzFSJJtt6sAEMz43bodXuYh74sQUL+9fxPebdt17dvHgboIIQNIKiuzgiZ4MZ5Bf+OX0mPNfZ7WtPLLMM75MnEjihp7JpBXtj1DxLrYHj5aiNFcCmouNTTjuK/Sh/PAGHBMkqfjS+f2sPivU22RZWiSRldmlX6i9mEm9iGnz+NHVkf13ZpFfsLmPQAc3aMFYCQQcrmi43ePR3t8+go+d2c7XEDOh8GEVCrMaQr2RshzNeoyGQ31MrxQ/0XXM6N1qvaMiVRJzy3AoBr//xUKh1rb9g49ntbzsG8Te9V7xo0Z4Bu3Yp31Mb1dCGZOOFJP8ZXm9mG9jPy4PqrBfNE2SHMy2TEXIMI4upSq+n6j6SGraa8uI5EPtaerc18oGiHR5CPJVH5PCt8="
    # OSSRH_JIRA_PASSWORD
    - secure: "wGRSWxIeehKG2XjuwNs2ijutdJn6L8thHaOC9w1PDg5p4LwcWER+6g7qVVPvBBY0nZFP3GwIylcMmuV3DoYh4qIOeUPpyXL84Q5TDBP0WBQZ8o8mSx7b1MPxc6ztd6cvtWT9wNiTeaCkZfn2wm1CShkjFvE4EIgchgG+e9t8g05zJEjsvTAVN411cRnHNiN66yXY4WkMoPgoLWb59Zyo1AneYJpu9ZZtj74TrIrug2ff6vfFerxjh2q2D6ywcVJ2GUb0qAqGYtES3Oab3fct4WFQ4QpTpA7Z75vwFoDQlPBV6g+x9ubIg9A5TpPTUar2oRt6+0e6XkEdvU4YeaL1qKXpH39CCROwM0kPBBk1v2lEuKcZMyIne2BC8w2oAkWR0newRC7y+2DIyzS0JSBDZ6ueSYF2tMvTDUai5e+jK4y1caEJPeZ/D81KZ8wApyLK/FZcagM4iDO05RR3nvPzYewl6tBO1+sUwi9lNx62wpdDMoaUBIoqTTw4LXAkLw7M6QUKwy7R//02/ipY91Fx+3c+zY6kKZ/KYEl+alxSrVANwDfWL6cOTucStb7CZMdOlTC6IdpEfeco80GD3MQwC8c4aY+GMH415UaW2WKohW98ySUw2de655LGMjNK97bI2MBIww00KrInkGfc293Ohq1g1oA3Z7vnvrbk9bSxoWA="
    # GPG_KEY_NAME
    - secure: "V/QdZtDvLaqexqNOOMB/O829TDglx4W7yEXN++9KT+nsC30J9UPz78Xwt0bgJt5uBA1BUkMnIcxdMJga48kfYhjLFtaVYy4HIxdnBOTJdTf870sbQteCrBKPnIitOMdYKEzyCyrYQEXjYe/QQ/Gp8T0Zf7GYGC0Jg4wtgApHmWtgZ+s4ZVpiL6dsxp8IifkpLDNMA+jGPzz/TNd7Dz5TzsiV8d1UBUetSiJ6aayqXuf111ffXblKAhKQlULrInmWTHIhWJqHD8yJlQKv2yVQPw59ou21ATTGBIDohvgrFkGxezR0jqQWgJchBIbTcpwc5zrn3kELriSsJVFaQcZSVd2b3qzsNtPHBYyOSFTIjfdiuvvQKYtL7/i/k31tc+UQVty1uSRnWAjSUqSwxy3/NUpSaZhJ43fpKd5uQjJtXHX4rnGi6xxENH71638og837AI/wAPL0c7CJqXHEhZ4OaomWnXkCR5GTNk43R8L1/gnX905KpL1Q3hHjNzRzaSdJg/85NMkqyAh7kcDVtcsZn6VK66WY7KREjEmOKZfICAlqgUwDWRGuaSZ8ysqn6P1DW0kANXT6xcfjn3vYf7Psr1DqoTTflKFe0H8o6NKaxYv2eCr5xr4aQsOKtTvTbMzuR+EYacLlged1qWmzQB3QiA+S3RfwDfWmy6SsQOQFoMs="
    # GPG_PASSPHRASE
    - secure: "JfgR0GzG9SVq57MX0AnC3w9mHYDAN8teVjzC+2CxHwmH0wGTSfMh4moI3ivlcB3haYxLLoCPyBOqW2XgabYXVgC/i65AH4Uri0Pqt73LhTWC6rR5/6IYTjhiWmZiwwjKniwJRfJb20JQuAyz3PHvvrtNGwdmafJTR4dAhmEBHB7vYfqp0I/sAorUIIUCVMO4U4lRnSfU+OpiTXib6QVS3tHLLVJxaaGALDarWywBj+O7iDp+LZQz/muBoDW+TzYbjzCXCjws9aSSQcqPZPcOpGvDoefSRASt8VHtVIuF5zvm8Gw4mMLTvchN20tGjeho6ZRt/1ttxVDIxczFSCCV7UklBPvBfOu+XTsjD2ZSHZQnTrlL3SrRUZ/F+AJBYicuk5npZHxTj+PPSSc7nijt9PjxE8ITwQhtFHBMwKMUD8fOg0uD0TrXCyTCXcJETlCXlrBSliZexx6khXxEomNCQTIRm/BwwnhGA0IbPqazvwdoQ3O3BQV+xblrf+4ToHdQhtmMqqJGfuNdL1v+NyK553LBHPz6XRGLlPb1yiMjsNeaXBiak9bMpBJ5MpeOYjEBKNFgrlBmpMxm5foR+EXili8FeNPYLoRNZRgcxnaEvHOfqx5Ic9oIhrsvD/oIRVdOpRdrNf+G0fnvmwhPfK7y5K2EkD93j95GZoBlm1KD9Tc="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
