language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "Epe3K9J8/TtrR/RnfLc4kTI8W9jHbW39riiaSqUTngnUL/NNNhIIMS1BEtqD6ALKM0cCMpWcFg/VAkbaLY75ExkBaE8T3tltjh/zPv3hv5Z4u6UfP7bIKHP55aplbph9YCl2ROQOWVvpHNauPR4OlQcEFymDeL3cl9dM4HvV6MeXERJwj8AzLzEmp41HHQgfVOFhomOHDIVMM9m10qA8LIVtb3F59SxcwvBJ143kV7D3oI1Xy4ChWRXHxkDOzVEVx6ADNnygT5yRKUwWb7IgvuozqvoKtddUV+89cYFt6yUt5b2mF6vcbwTyN3g7CwNDMn9uv3DyNmmItUAKEjtZ21bTVRdF0lhhNxIBPgcW9VYcmIo0oBG4tW+O0YDbVX9AfUego0zHAYUa9RFXUiwg/WetkPxs+urRpkck34ecXVIdCUf7/T12NuP/EhRdHX+9v5BitJZhxG2UoABw6uwnq8DKHQzJsP61IwaJOLa+JLSz2v9vcShTw9CjI/eZkR9x8qd9ZsShKh5eoW9COOjKFXn/HYMTKy+Ipz0MCFwyHViDrqQfLq5iCEgVHHHh/WEs6R3/oJvZLywyVR+EZ4+ObSOzCuES34XXZ+zEFj3wNCSvSjqAtqrl3TbnU/yCOXSvSu7REebj2Zs37Q+jVLXRcnlVXAcvFiFLDH3u2uyjv+U="
    # OSSRH_JIRA_PASSWORD
    - secure: "wGRSWxIeehKG2XjuwNs2ijutdJn6L8thHaOC9w1PDg5p4LwcWER+6g7qVVPvBBY0nZFP3GwIylcMmuV3DoYh4qIOeUPpyXL84Q5TDBP0WBQZ8o8mSx7b1MPxc6ztd6cvtWT9wNiTeaCkZfn2wm1CShkjFvE4EIgchgG+e9t8g05zJEjsvTAVN411cRnHNiN66yXY4WkMoPgoLWb59Zyo1AneYJpu9ZZtj74TrIrug2ff6vfFerxjh2q2D6ywcVJ2GUb0qAqGYtES3Oab3fct4WFQ4QpTpA7Z75vwFoDQlPBV6g+x9ubIg9A5TpPTUar2oRt6+0e6XkEdvU4YeaL1qKXpH39CCROwM0kPBBk1v2lEuKcZMyIne2BC8w2oAkWR0newRC7y+2DIyzS0JSBDZ6ueSYF2tMvTDUai5e+jK4y1caEJPeZ/D81KZ8wApyLK/FZcagM4iDO05RR3nvPzYewl6tBO1+sUwi9lNx62wpdDMoaUBIoqTTw4LXAkLw7M6QUKwy7R//02/ipY91Fx+3c+zY6kKZ/KYEl+alxSrVANwDfWL6cOTucStb7CZMdOlTC6IdpEfeco80GD3MQwC8c4aY+GMH415UaW2WKohW98ySUw2de655LGMjNK97bI2MBIww00KrInkGfc293Ohq1g1oA3Z7vnvrbk9bSxoWA="
    # GPG_KEY_NAME
    - secure: "PP+RG5Ah+FUb9jxj//Ff3Oaq0N72bfMD63UEscHKXV8aE9czFjU/FGiYHtjZUEbiVA25gi6YTH5AZFl5f2pyFUqbeL5hoH5fzj60NP2Tfz8L9oTG/h2XtVXccPTV4xq7+AOMTGEBoFDzVac1eqoT99wtGDMmcCypyYq8dP/s3pnqrnNmJl/Q/BNn/rpwRjVJ0JIX8fGPRuK36BkBunHlYZ5MBwXfamoAQoqtbzh1ful+PASTaNZA9eXZkZx9VKSFvnmnXsEdrwpfeYsG0sBVPrRsWVBEvjOXZkoA9jbFYHmLsSPtCBnhGSybUHQ9zoVwkGJ1O46fcUICagoN7Dbza+ThMaxmaU9a6UaCYCyOO2QHfD5d24jCO9eWRWEuRTAC16CnIs0vrxM3A/EStduTTguq/2uUCQvt/sK5cGl2rKMITvnPgQXeOTe6lLc51a9w5qliRBJt90EbB7iYL6Cnv9brg1uHco3RPHyFEx4NwbuhGsZ884y/OJtfiqnVC3M6npjam0sJFWjUBCllJWxfCArjxuoWgtIUJJN71smtSPnALrXrPO/nWM7efAQSZ6dQWi6BUiU/+bTyGHQN0ZkDQAy0++nXywL+2X2BG9vnCD44B9SFNfJGlRVdEhDJrdyhzV3m71zYv8CTFdA6X12WpmBKwWmiaAaCw6UEdgo7qJ0="
    # GPG_PASSPHRASE
    - secure: "XZ1PX3CrHJCtraDxxoMxM8BJnsR7zW/ZjzOD1W5EiXVR4Gp82Dlam6tpU/yg/Y8JAdSNvy+9uQ6DNl1nkkuUAodxElLn4v+B9KUAmsWrGl9NuC1P9m3br1zzVs1NLB7JnJhHlQ1gNlMAg5YWKxgsGhpag0Man0GIB1X9VFEs7F8PYpB0ArIehTvYDNFeKsQ7QVPrH788vsLuVwyiGIDFnqzRUYgAwdQyR0dBoR8/lXgJo7YAkoCp0WVpbOz84mYQZPharxsJRlrDRC+E+zmA2fP8Gm6Zai/GRa01lXgHvupo4+EVKld6+z4kWYI0s7ASXHEFu5hNiSSrW2/3zCcT2E1JkbFSybmyp+g8DFAUerdaL6gQrOS7jYH483Y3ZhEjlB9YQisVmXQY16Yg5PNbjMJ8kLlTHXyoUdRWDSDqC/4JYyDdR/JVDQqE9jzxqOKYHOMzVASUFvLE2TanHS46P4+xAOLeGl7gsFzeNVx6SxmSe0c6XiH/znyUuXzXrWIeBCfbEaDdfeGiIC5ddAYptayQcIGkGXlQwa2zucrRljaKA3UYTjrKyEXGBdqPF/5pWpjDvu2Stu6Sni2ejksz0Dr/K5iQZeuTPsqn9KotqteLcM2Yhs1tKX2N40fwvYe1GSAAio3HS4KDuoHKvgEOuLH3hq6UATgGp+b93arZA+0="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
