language: java

sudo: false
os:
  - osx
jdk:
  - openjdk11

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "UZHvFtGtCiz72cq8R+igvvKWtHxV+UthL4QQFH1vuj2l1phSOCSVZAw973xW9MSEYE+ur6Tr+TSQ0er41uApdmq2gwcojH0xi6N4zfDKVC1q25p3v3p7PGsUPpIZeF9u5vbGIZGghfA/KJ4/Pb1aik9UIYO4kyL3GQPGaNw4ZrivEdvmzzWVSXUn25seZ5+XBNoLmi/mzWFJ7iy+cNTQCvc2ljMotpY6P9Fz4ZpFfDqUe35nVcXu6SmtjpxBIcATYlNrDOjCjIhRF0xtXxdik/RTFnod1REv6QzFSJJtt6sAEMz43bodXuYh74sQUL+9fxPebdt17dvHgboIIQNIKiuzgiZ4MZ5Bf+OX0mPNfZ7WtPLLMM75MnEjihp7JpBXtj1DxLrYHj5aiNFcCmouNTTjuK/Sh/PAGHBMkqfjS+f2sPivU22RZWiSRldmlX6i9mEm9iGnz+NHVkf13ZpFfsLmPQAc3aMFYCQQcrmi43ePR3t8+go+d2c7XEDOh8GEVCrMaQr2RshzNeoyGQ31MrxQ/0XXM6N1qvaMiVRJzy3AoBr//xUKh1rb9g49ntbzsG8Te9V7xo0Z4Bu3Yp31Mb1dCGZOOFJP8ZXm9mG9jPy4PqrBfNE2SHMy2TEXIMI4upSq+n6j6SGraa8uI5EPtaerc18oGiHR5CPJVH5PCt8="
    # OSSRH_JIRA_PASSWORD
    - secure: "wGRSWxIeehKG2XjuwNs2ijutdJn6L8thHaOC9w1PDg5p4LwcWER+6g7qVVPvBBY0nZFP3GwIylcMmuV3DoYh4qIOeUPpyXL84Q5TDBP0WBQZ8o8mSx7b1MPxc6ztd6cvtWT9wNiTeaCkZfn2wm1CShkjFvE4EIgchgG+e9t8g05zJEjsvTAVN411cRnHNiN66yXY4WkMoPgoLWb59Zyo1AneYJpu9ZZtj74TrIrug2ff6vfFerxjh2q2D6ywcVJ2GUb0qAqGYtES3Oab3fct4WFQ4QpTpA7Z75vwFoDQlPBV6g+x9ubIg9A5TpPTUar2oRt6+0e6XkEdvU4YeaL1qKXpH39CCROwM0kPBBk1v2lEuKcZMyIne2BC8w2oAkWR0newRC7y+2DIyzS0JSBDZ6ueSYF2tMvTDUai5e+jK4y1caEJPeZ/D81KZ8wApyLK/FZcagM4iDO05RR3nvPzYewl6tBO1+sUwi9lNx62wpdDMoaUBIoqTTw4LXAkLw7M6QUKwy7R//02/ipY91Fx+3c+zY6kKZ/KYEl+alxSrVANwDfWL6cOTucStb7CZMdOlTC6IdpEfeco80GD3MQwC8c4aY+GMH415UaW2WKohW98ySUw2de655LGMjNK97bI2MBIww00KrInkGfc293Ohq1g1oA3Z7vnvrbk9bSxoWA="
    # GPG_KEY_NAME
    - secure: "fiQQsQ3DxzF4raLgH2SRo68PUg4DobY5REyrn43t2xcMjMqe3trduRkyYBGc5hHriWhUC5w8FWmtT27gKqFZNHU0HVwrGx8Kx9BH/NlCrnWv4D8jhMvxlalLrsEOniRtosS8+6ynPNHXwHxXYj6O0ZFjpDNX/PDIMg9T0VmGnLFeCWptesHBniqr2ogjHm4Jw3g2+LFRIOlNun68h0OWtjmC232FuHkB5VKJJr+p/i5gc1/P8bAxj6hEt05SDWMFpEn3EQJW8MsWdPlTu1YTD3tSTjCkapEUo22Wo2YTiDb43bheQh4lhYmEeGwKY+MIpjtrUKhv4E+Q16tAKxn+xFl1csoLhHCim+PzI8+rEtPNmyvwRlHu48uZapF7O+3dSyFfFRTjIvKLGMaTOi6Tzq0cUQBAMAw8kJNWs/Ng7Jphf1EclrC7C/+K6zCUiVwdCw+APQim+gZRTAw0mLCMg4t3ZzpHnkqsuhTynyWvJtOMeAlYhDLzsecle1YAMYWjaH3vrmiPtOBni2SfYG9zvgqGwMkZs/9aVk2p/+33uxggwVQMk1kiypR1edruPur2j/q9kk4IVBpHNJD+zWpgQew+yz0cOktE3o04NCtyn6Us+2VClkZOQsndte1OfBWACGSQYH3pRqTX8ORQ8tIm8EKpIdbX5XzHD+fn3HuKjCE="
    # GPG_PASSPHRASE
    - secure: "OkZII1SRX4fJBqD2Kj4WLaMqa9+DyUmlJrS9Er7cYY7knHPIpyEMVeL9WuK2BoDbJ0dGPhM29GlxaxmmGaAEPaNTYWo24obxUj/scg3fhgz0NCeuVjC8JS3xH6Ope/t7ubz3kdbPHTuiDlHLwo9PCNwHQzjGmGV9BHJNvbsuZJdmiItd/RQ4/wMROq1tnzt4mHVx8NQ4Ixr+vpQ40i7/GymVguvrwy+MVm3TNyaErhJTopL8UhCthLyeeUcEDlvE9LIKOZ3hH/HSGiCkAgvT8apTm3ymLzkqatjRhF74GosGUaCNffQKSRnYsitHp2YQ8PLhhA6sv7Lxb8nQTgkqwsr6Spx8WRO5QsvpER0rXpFApFukvQ7M6uhykXc3PMRdkERlLVqi/RFuhmDFTAfJdUP8Uaj/e5J3Zs7FPWpP4+gJa4e3avD+J55FxZeEfaEWuX9NL8jLxxb/NLQctPsYubvwqu5LrkQcZCK+UmRJlER485l0LKHpKpfBa0Gjqln1Srtp5/hkiwoDcx5yQosAKxTrxSNDFVsih9xjhOQyFZeJPyNjbdVul4RWnqcn3HFyaYcMpeqg9zDra55zIVsfF1ijoWEZKH58kESgTLV7yt4KDUVPGHFVoqOm/wTELa+4HC7UtqQTaK1N+7U3t/bUY16M+C0PAerc7uQ2YbVoHZE="
stages:
  - name: deploy
    if: branch = master

after_success:
  - >-
    test $TRAVIS_BRANCH = "master" &&
    ./cd/before-deploy.sh &&
    ./gradlew --version &&
    ./gradlew --info publish
    -PjiraUsername=$OSSRH_JIRA_USERNAME
    -PjiraPass=$OSSRH_JIRA_PASSWORD
    -Psigning.keyId=$GPG_KEY_NAME
    -Psigning.password=$GPG_PASSPHRASE
